
name: Deploy to Artifactiry

on:
  release:
    types: [created]
  schedule:
    - cron:  '0 1 * * 1' # Run every Monday at 1:00
#  push:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml -s settings.xml

      - name: Publish to Artifactory
        run: mvn deploy -s settings.xml
